### ISSUE TITLE
DissScenarioLoad: persisting of model breaks final display of metrics in the console

### ISSUE THREAD

**Issue by maxkratz** [Echtzeitsysteme/iflye#81]
https://github.com/Echtzeitsysteme/iflye/blob/main/vne.scenarios/src/scenarios/load/DissScenarioLoad.java#L156-L158

**Comment by maxkratz** [comment]
Example:
```
java.nio.file.NoSuchFileException: ./metrics/test.csv
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2988)
	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3036)
	at scenario.util.CsvUtil.writeCsvLine(CsvUtil.java:244)
	at scenario.util.CsvUtil.appendCsvLine(CsvUtil.java:159)
	at scenarios.load.DissScenarioLoad.main(DissScenarioLoad.java:136)
```
