### ISSUE TITLE
DissScenarioLoad: loading of non-existing file throws IllegalArgumentException with no description

### ISSUE THREAD

**Issue by maxkratz** [Echtzeitsysteme/iflye#82]

**Comment by maxkratz** [comment]
E.g.:

```
=> Arguments: [-a, gips, -o, total-comm-c, -e, emoflon_wo_update, -l, 2, -k, 1, -s, resources/two-tier-4-pods/snet.json, -v, resources/10-vnets/vnets.json, -c, ./metrics/test.csv, -i, 600]
=> Using max path length 2
Exception in thread "main" java.lang.IllegalArgumentException
	at model.converter.FileUtils.readFile(FileUtils.java:78)
	at model.converter.FileUtils.readFileToJson(FileUtils.java:41)
	at model.converter.IncrementalModelConverter.jsonToModelIncremental(IncrementalModelConverter.java:41)
	at scenarios.load.DissScenarioLoad.main(DissScenarioLoad.java:119)
```
